/**
 * Images generated by @copylee/dsh-image-gen, embedded in a reply as
 * `![caption](genimg:<job id>)`. The job may still be running (a background
 * generation) — even after the reply finished streaming — so the renderer polls
 * the plugin's job route and shows a placeholder at the expected aspect ratio
 * until the image is ready.
 */
import { useEffect, useState } from 'react'

export const GENIMG_SCHEME = 'genimg:'
/** dsh-image-gen's job route, relative to the DSH page (web and `dsh-app://app/`). */
const JOBS_ROUTE = 'plugins/copylee-image-gen/jobs/'
const JOB_ID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/
const POLL_MS = 1500
const MAX_POLL_MS = 10_000

export interface GeneratedJob {
  status: 'pending' | 'done' | 'failed'
  /** Real dimensions when done; the expected ratio while pending. */
  width: number
  height: number
  error?: string
  /** The finished image on disk (dsh-image-gen's workspace or gallery copy). */
  path?: string
}

/** Settled jobs, so a remounted node (streaming re-parses) never flashes back to the placeholder. */
const settled = new Map<string, GeneratedJob>()

export function isGeneratedImage(src: string): boolean {
  return src.startsWith(GENIMG_SCHEME)
}

/** The job id of a complete `genimg:` reference; undefined while it is still streaming in. */
export function generatedJobId(src: string): string | undefined {
  const id = src.slice(GENIMG_SCHEME.length).trim().toLowerCase()
  return JOB_ID.test(id) ? id : undefined
}

export function jobStatusUrl(id: string): string {
  return new URL(`${JOBS_ROUTE}${id}`, document.baseURI).href
}

export function jobImageUrl(id: string): string {
  return new URL(`${JOBS_ROUTE}${id}/image`, document.baseURI).href
}

function parseJob(value: unknown): GeneratedJob | undefined {
  if (typeof value !== 'object' || value === null) return undefined
  const job = value as Record<string, unknown>
  if (job.status !== 'pending' && job.status !== 'done' && job.status !== 'failed') return undefined
  const width = typeof job.width === 'number' && job.width > 0 ? job.width : 1
  const height = typeof job.height === 'number' && job.height > 0 ? job.height : 1
  return {
    status: job.status, width, height,
    ...(typeof job.error === 'string' ? { error: job.error } : {}),
    ...(typeof job.path === 'string' && job.path !== '' ? { path: job.path } : {}),
  }
}

const PENDING: GeneratedJob = { status: 'pending', width: 1, height: 1 }

/**
 * Poll one job until it settles. Network errors back off and keep polling (the
 * Host may be restarting); a route that is missing altogether (dsh-image-gen not
 * installed) settles as failed.
 */
export function useGeneratedJob(id: string | undefined): GeneratedJob {
  const [job, setJob] = useState<GeneratedJob>(() => (id === undefined ? undefined : settled.get(id)) ?? PENDING)
  useEffect(() => {
    if (id === undefined) return undefined
    const known = settled.get(id)
    if (known !== undefined) {
      setJob(known)
      return undefined
    }
    let stopped = false
    let timer: ReturnType<typeof setTimeout> | undefined
    let delay = POLL_MS
    const poll = async (): Promise<void> => {
      let next: GeneratedJob | undefined
      try {
        const response = await fetch(jobStatusUrl(id), { credentials: 'same-origin', cache: 'no-store' })
        const json = (response.headers.get('content-type') ?? '').includes('json')
        // A 404 or the SPA's HTML fallback: no job route answers this page.
        next = response.status === 404 || (response.ok && !json)
          ? { status: 'failed', width: 1, height: 1, error: 'image generation plugin unavailable' }
          : response.ok ? parseJob(await response.json()) : undefined
      } catch {
        next = undefined
      }
      if (stopped) return
      if (next !== undefined) setJob(next)
      if (next !== undefined && next.status !== 'pending') {
        settled.set(id, next)
        return
      }
      delay = next === undefined ? Math.min(delay * 2, MAX_POLL_MS) : POLL_MS
      timer = setTimeout(() => { void poll() }, delay)
    }
    void poll()
    return () => {
      stopped = true
      if (timer !== undefined) clearTimeout(timer)
    }
  }, [id])
  return job
}

/** Test hook: forget settled jobs. */
export function resetGeneratedJobs(): void {
  settled.clear()
}

/** DSH ships zh/en UIs; follow the document language, then the browser's. */
export function generatedLabels(): { generating: string, failed: string } {
  const lang = typeof document === 'undefined' ? '' : document.documentElement.lang || navigator.language
  return lang.toLowerCase().startsWith('zh')
    ? { generating: '图片生成中…', failed: '图片生成失败' }
    : { generating: 'Generating image…', failed: 'Image generation failed' }
}
